### PR TITLE
Test Db connection

### LINKED ISSUE #9: Connect the server with mongodb database using mongoose

### PR DESCRIPTION
**Pull request by Ayobami6**

### CODE REVIEW

**Review by jojothomas1515 — COMMENTED** [review]
I like the fact that the app running is dependent on the database connecting

**Comment by Ayobami6** [comment]
Yeah, Me too

**Review by Utilitycoder — APPROVED** [review]
I think we can merge if it works fine when you tested

**Comment by Ayobami6** [comment]
Yes we can, Just wanted everyone to participate in the review

**Pull request merged**
